# Generated by Django 6.1.1 on 2026-10-06 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_no', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('asset_type', models.CharField(choices=[('laptop', '筆記型電腦'), ('desktop', '桌上型電腦'), ('monitor', '螢幕'), ('phone', '手機'), ('printer', '印表機'), ('network', '網路設備'), ('other', '其他')], max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('available', '可用'), ('in_use', '使用中'), ('maintenance', '維修中'), ('retired', '已報廢')], default='available', max_length=20)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='accounts.department')),
            ],
        ),
    ]
