from django.contrib import admin
from django.urls import (
    include,
    path,
)

from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)

from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularSwaggerView,
)

from accounts.views import (
    CurrentUserAPIView,
    ITStaffListAPIView,
    AssetAssigneeListAPIView,
    DepartmentListAPIView,
)

from accounts.system_management import (
    SystemUserListCreateAPIView,
    SystemUserDetailAPIView,
    SystemDepartmentListCreateAPIView,
    SystemDepartmentDetailAPIView,
    SystemTicketCategoryListCreateAPIView,
    SystemTicketCategoryDetailAPIView,
    system_management_page,
)

from tickets.views import (
    ticket_create_page,
    ticket_detail_page,
    ticket_list_page,
    dashboard_page,
    reports_page,
)

from assets.views import (
    asset_list_page,
    asset_detail_page,
    asset_create_page,
)

urlpatterns = [
    path(
        "admin/",
        admin.site.urls,
    ),
    path(
        "api/schema/",
        SpectacularAPIView.as_view(),
        name="schema",
    ),
    path(
        "api/docs/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    path(
        "api/auth/login/",
        TokenObtainPairView.as_view(),
        name="token_obtain_pair",
    ),
    path(
        "api/auth/refresh/",
        TokenRefreshView.as_view(),
        name="token_refresh",
    ),
    path(
        "api/auth/me/",
        CurrentUserAPIView.as_view(),
        name="current-user",
    ),
    path(
        "api/users/it-staff/",
        ITStaffListAPIView.as_view(),
        name="it-staff-list",
    ),
    path(
        "api/users/asset-assignees/",
        AssetAssigneeListAPIView.as_view(),
        name="asset-assignee-list",
    ),
    path(
        "api/departments/",
        DepartmentListAPIView.as_view(),
        name="department-list",
    ),
    path(
        "api/admin/users/",
        SystemUserListCreateAPIView.as_view(),
        name="system-user-list-create",
    ),
    path(
        "api/admin/users/<int:pk>/",
        SystemUserDetailAPIView.as_view(),
        name="system-user-detail",
    ),
    path(
        "api/admin/departments/",
        SystemDepartmentListCreateAPIView.as_view(),
        name="system-department-list-create",
    ),
    path(
        "api/admin/departments/<int:pk>/",
        SystemDepartmentDetailAPIView.as_view(),
        name="system-department-detail",
    ),
    path(
        "api/admin/ticket-categories/",
        SystemTicketCategoryListCreateAPIView.as_view(),
        name="system-ticket-category-list-create",
    ),
    path(
        "api/admin/ticket-categories/<int:pk>/",
        SystemTicketCategoryDetailAPIView.as_view(),
        name="system-ticket-category-detail",
    ),
    path(
        "api/",
        include("tickets.urls"),
    ),
    path(
        "api/",
        include("assets.urls"),
    ),
    path(
        "",
        include("accounts.urls"),
    ),
    path(
        "dashboard/",
        dashboard_page,
        name="dashboard-page",
    ),
    path(
        "reports/",
        reports_page,
        name="reports-page",
    ),
    path(
        "system/",
        system_management_page,
        name="system-management-page",
    ),
    path(
        "tickets/",
        ticket_list_page,
        name="ticket-list-page",
    ),
    path(
        "tickets/create/",
        ticket_create_page,
        name="ticket-create-page",
    ),
    path(
        "tickets/<int:pk>/",
        ticket_detail_page,
        name="ticket-detail-page",
    ),
    path(
        "assets/",
        asset_list_page,
        name="asset-list-page",
    ),
    path(
        "assets/create/",
        asset_create_page,
        name="asset-create-page",
    ),
    path(
        "assets/<int:pk>/",
        asset_detail_page,
        name="asset-detail-page",
    ),
]
