# Generated by Django 6.1.1 on 2026-10-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
