# Generated by Django 6.1.1 on 2026-10-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ticket_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
