# Generated by Django 6.1.1 on 2026-10-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_tickethistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_note',
            field=models.TextField(blank=True),
        ),
    ]
