# Generated by Django 6.1.1 on 2026-10-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_resolution_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickethistory',
            name='new_value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_value',
            field=models.TextField(blank=True),
        ),
    ]
